### ISSUE TITLE
killsnoop-nd_example.txt question

### ISSUE THREAD

**Issue by rustjson** [brendangregg/systemtap-lwtools#1]
Hey, I found your repo by [here](https://sourceware.org/systemtap/examples/keyword-index.html), And this repo was helpful. But I have a question here
Here is the output:

``` bash
FROM   COMMAND      SIG   TO     RESULT
17468  php          15    17469     646
17484  zsh          0     17485  935480032
17484  zsh          0     17485       0
17484  zsh          0     17486  1033139520
17484  zsh          0     17486       0
17487  zsh          0     17488  1033134208
17487  zsh          0     17488       0
17487  zsh          0     17489  1033139520
17487  zsh          0     17489       0
17484  zsh          0     17487  935480032
17484  zsh          0     17487       0
8774   zsh          0     17484  1033136864
8774   zsh          0     17484       0
```

The second line was helpful, But there are so many zero followed by that. What does that means?
Many thanks

**Comment by rustjson** [comment]
I am using this stp file: https://sourceware.org/systemtap/examples/lwtools/killsnoop-nd.stp

**Comment by yangoliver** [comment]
Here is an exmaple,

```
17484  zsh          0     17485  935480032
```

For process zsh(17484), it send signal 0 to process(17845),  and return value of kill() is 935480032.

See man page of ftrace version killsnoop here,

https://github.com/brendangregg/perf-tools/blob/master/examples/killsnoop_example.txt

**Comment by rustjson** [comment]
https://github.com/brendangregg/perf-tools/blob/master/examples/killsnoop_example.txt#L44

``` bash
On the last line: there wasn't a nice signal name for signal 0, so just numeric
0 is printed. You'll see signal 0's used to check if processes still exist.
```

@yangoliver  Thanks
